-- AULA 31-03 CRIACAO DE BANCO DE DADOS E TABELAS

-- CRIACAO DO BANCO DE DADOS AULA3103

CREATE DATABASE AULA3103;

-- ABERTURA DO BANCO DE DADOS PARA USO

USE AULA3103;

-- CRIACAO DA TABELA PRIMEIRA_TABELA
CREATE TABLE primeira_tabela(
	primeiro_campo int,
    segundo_campo char(26)
);

