-- EDUARDO FERREIRA BONIFACIO ARQ3029115 TSI 
USE EMPRESA;
-- A
INSERT INTO FUNCIONARIO 
(CPF, NOME, SALARIO, DATANASC, RUA, NUMERO, COMPL, BAIRRO, CIDADE, ESTADO, CEP, SEXO)
VALUES 
('999', 'Roberto Carlos', 4500, '1972-06-21', 'Rua Benjamin', 34, NULL, 'Vila Maria', 'Santo André', 'SP', '1', 'M');

-- B
INSERT INTO DEPARTAMENTO (DNUMERO, DNOME)
VALUES
(1, 'Producao'); -- Erro de inserção devido a pedir para inserir um DNUMERO que já existe cadastrado na tabela.

-- C
INSERT INTO DEPARTAMENTO (DNUMERO, DNOME, CPFGERENTE)
VALUES
(10, 'Producao', '999'); 

-- D
DELETE FROM FUNCIONARIO WHERE CPF = '999'; -- O funcionário está inserido em outra tabela, o que impede que seja deletado.

-- E
UPDATE FUNCIONARIO SET DNUMERO = 20 WHERE CPF = '999'; -- Não há departamento 20.

-- 4
INSERT INTO DEPARTAMENTO (DNUMERO, DNOME)
VALUES (2, 'Ensino');

-- 5
INSERT INTO DEPARTAMENTO (DNUMERO, DNOME)
VALUES (3, 'RH');

-- 6
UPDATE FUNCIONARIO SET DNUMERO = 2 WHERE CPF = '1234';

-- 7 
UPDATE FUNCIONARIO SET DNUMERO = 3 WHERE CPF = '6668'; 

-- 8 
INSERT INTO ATRIBUICAO (CPF, PROJNUMERO)
VALUES 
('1234', 5),
('9998', 5),
('9879', 5);

-- 9
SELECT * FROM ATRIBUICAO WHERE PROJNUMERO = 4;
UPDATE FUNCIONARIO 
SET SALARIO = SALARIO * 1.1
WHERE CPF IN (SELECT CPF FROM ATRIBUICAO WHERE PROJNUMERO = 4);

-- 10
INSERT INTO DEPARTAMENTO (DNUMERO, DNOME, CPFGERENTE)
VALUES
(6, 'Marketing', '6668'); 

INSERT INTO PROJETO (PROJNOME, PROJLOCAL, DNUMERO)
VALUES 
('Call Center', 'São Paulo-SP, Rio de Janeiro-RJ e Campinas-SP', 6);

INSERT INTO ATRIBUICAO (CPF, PROJNUMERO)
VALUES 
('9876', 7),
('9879', 7),
('3334', 7),
('9998', 7),
('4534', 7);

select * from DEPARTAMENTO;
SELECT * FROM ATRIBUICAO;
SELECT * FROM PROJETO;
